### ISSUE TITLE
Eventgen errors

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom-data-generator#2]
Seeing occasional errors whilst running eventgen:

`
Fatal Error due to java.lang.RuntimeException: Failed to process
java.lang.RuntimeException: java.lang.RuntimeException: Failed to process
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at stroom.datagenerator.EventGen.go(EventGen.java:77)
        at stroom.datagenerator.EventGen.main(EventGen.java:207)
Caused by: java.lang.RuntimeException: Failed to process
        at stroom.datagenerator.EventGen.lambda$go$3(EventGen.java:84)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.io.IOException: Error: Unable to rename temp output file output/ausearch/TEST-RHEL5_6_AUSEARCH-EVENTS.2020-10-20T11:10:00Z-ausearch.zip-incomplete to output/ausearch/TEST-RHEL5_6_AUSEARCH-EVENTS.2020-10-20T11:10:00Z-ausearch.zip
        at stroom.datagenerator.EventStreamProcessor.process(EventStreamProcessor.java:236)
        at stroom.datagenerator.EventGen.processTimePeriod(EventGen.java:96)
        at stroom.datagenerator.EventGen.lambda$go$3(EventGen.java:79)
        ... 10 more
`

Command being run is `bin/eventgen config/events/ausearch.yml daily state DAY 2020-06-01 ROLLING -s 20
`

**Comment by gcdev373** [comment]
Possibly fixed with change to `removeIncompleteOutput` in v0.13

**Comment by gcdev373** [comment]
@stroomdev00 confirmed fix following testing.
